# Generated by Django 4.2.4 on 2023-08-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('authentication', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
