# Generated by Django 4.2.4 on 2023-08-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoj', '0002_userdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='numbers',
            field=models.CharField(max_length=100),
        ),
    ]
