# Generated by Django 4.2.4 on 2023-08-16 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khoj', '0003_alter_userdata_numbers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='numbers',
            new_name='input_values',
        ),
        migrations.AddField(
            model_name='userdata',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 22, 10, 25, 921336)),
        ),
    ]
